FROM php:8.2-fpm

# Устанавливаем рабочую директорию
WORKDIR /home/gaga/proj3

# Копируем composer.lock и composer.json
# COPY composer.lock composer.json /var/www/
# for new project  composer.json  to create by  composer init

RUN     apt-get update && apt-get install -y \
	build-essential locales zip \
	jpegoptim optipng pngquant gifsicle \
	vim unzip git curl btop mc nano less \
	libpq-dev libonig-dev libzip-dev \
	libfreetype-dev \
	libjpeg62-turbo-dev \
	libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install pdo_mysql mbstring zip exif pcntl gd

# RUN apt-get install libapache2-mod-php php-mysql

# RUN apt-get install php-pear // est uje + --with-pear 

# !!! https://www.php.net/manual/en/install.pecl.pear.php
RUN pecl install redis-5.3.7 \
	&& pecl install xdebug-3.2.1 \
	&& docker-php-ext-enable redis xdebug

RUN apt-get install -y libmemcached-dev libssl-dev zlib1g-dev \
	&& pecl install memcached-3.2.0 \
	&& docker-php-ext-enable memcached

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#RUN groupadd -g 1000 www-data
#RUN useradd -u 1000 -ms /bin/bash -g www-data www-data 
# Копируем содержимое текущего каталога в рабочую директорию
COPY . /var/www
COPY --chown=www-data:www-data . /var/www
# Меняем пользователя на www
USER www-data

# В контейнере открываем 9000 порт и запускаем сервер php-fpm
EXPOSE 9000
CMD ["php-fpm"]
