version: '3.3'
services:

  # chown -R gaga:gaga /home/gaga/proj3
  # docker-compose up -d         // run  Daemon mode
  # docker-compose down          // Off
  # docker-compose up --build    // renew
  # docker ps
  # docker exec -it  -namecont- bash  (OR sh)
  # I love this project for dev purpose, I let you check more about it here: https://github.com/maildev/maildev
  # it's optional and I won't go in detail about it now
  mail:
    # скачать образ
    image: maildev/maildev
    container_name: proj3-maildev
    command: bin/maildev --web 8088 --smtp 1025 --hide-extensions STARTTLS
    ports:
      - "8088:8088"
      - "1025:1025"
    restart: "no"
    networks:
      - network3

  memcached:
    # скачать образ
    image: 'bitnami/memcached:latest'
    container_name: proj3-memcached
    networks:
      - network3

  httpd:
    # собрать образ и назвать proj3/httpd
    build:
      context: .
      dockerfile: Dockerfile_web
    image: proj3-httpd
    volumes:
      - ./src:/usr/local/apache2/htdocs
    container_name: proj3-httpd
    # раскомментируйте следующую строку, если вы запускаете это в продакшн среде
    # restart: unless-stopped
    tty: true
    ports:
#      - "8080:80"    if ports local  busy
#      - "8443:443"
      - "80:80"
      - "443:443"
    networks:
      - network3

  web:
    build:
      context: .
      dockerfile: Dockerfile_apache_php
    image: proj3-php-8.2-apache
    container_name: proj3-apache-php
    ports:
      - "8080:80"
    # раскомментируйте следующую строку, если вы запускаете это в продакшн среде
    # restart: always
    volumes:
      - ./src:/var/www/html
# FIRST copy from image
#docker cp proj3-apache-php:/usr/local/etc/php/php.ini-development ./config/php.ini
#docker cp proj3-apache-php:/usr/local/etc/php/php.ini-production ./config/php.ini
      - ./config/php.ini:/usr/local/etc/php/php.ini
# FIRST copy from image
#docker cp proj3-apache-php:/etc/apache2/sites-available/000-default.conf ./config/apache.conf
      - ./config/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - network3

  db3:
    image: mariadb:11.7.2
    container_name: proj3-mysql
    volumes:
      - /home/gaga/proj3/mysql:/var/lib/mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret1
    networks:
      - network3

  php:
    # собрать образ и назвать proj3/php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile_php
    image: proj3-php:8.2-fpm
    container_name: proj3-php8.2-fpm
    # раскомментируйте следующую строку, если вы запускаете это в продакшн среде
    # restart: unless-stopped
    tty: true
    #working_dir: /var/www
    volumes:
      - /home/gaga/proj3/local.ini:/usr/local/etc/php/php.ini
    # /usr/local/etc/php/conf.d/...
    networks:
      - network3

# Docker Networks
networks:
  network3:
    driver: bridge
