FROM php:8.2-apache

# Установка зависимостей и скрипта расширений
RUN apt-get update && apt-get install -y git curl unzip \
    && curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
        -o /usr/local/bin/install-php-extensions \
    && chmod +x /usr/local/bin/install-php-extensions

# Установка нужных расширений
RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    memcached \
    opcache
